### PR TITLE
Support common pipeline fields

### PR DESCRIPTION
**Pull request by alexander-veit**
This PR adds `common_fields` to MetaWorkflowRuns as well as `sequencing_center` to QualityMetric and WorkflowRun, so that it can be used as common field.

### CODE REVIEW

**Comment by alexander-veit** [comment]
I tried to add 
```
"sequencing_center": {
      "$ref": "mixins.json#/sequencing_center/sequencing_center"
}
```
to file properties in order to avoid having to add the mixin to every file sub-type, but that did not resolve correctly.

**Comment by drio18** [comment]
> I tried to add
> 
> ```
> "sequencing_center": {
>       "$ref": "mixins.json#/sequencing_center/sequencing_center"
> }
> ```
> 
> to file properties in order to avoid having to add the mixin to every file sub-type, but that did not resolve correctly.

You should be able to do this, but will require using the `$merge` referencing system instead of the `$ref` one.

**Review by drio18 — COMMENTED** [review]
Looks good. I think your idea of moving the reference to File properties makes sense, but needs the other reference style, as commented.

My one request is to add a test to ensure all properties under MWFR `common_fields` are in fact present on the required items (WorkflowRun, OutputFile, and QualityMetric). Happy to lend a hand here if you'd like.

**Comment by alexander-veit** [comment]
Good idea. I added a test.

**Comment by alexander-veit** [comment]
I redeployed this to wolf. It works with `$merge`. Thanks for the tip.

**Pull request merged**
