### PR TITLE
TOC Improvements for RST Content

### PR DESCRIPTION
**Pull request by utku-ozturk**
**PS:** This branch is based on [ui-dev4](https://github.com/smaht-dac/smaht-portal/tree/ui-dev4)

- `user_content.py` is updated to support multi-level TOC generation for  RST content
- `static_section.json` in master-inserts is updated to correct text and navigation URL in Next - Previous links under the TOC by creating directory pages.
- The top navigation bar's CSS has been updated to prevent level-1 (e.g., Documentation > User Guide) link clicks automatically generated after the directory page is created in the previous step.
- `Serkan Utku Öztürk `added to users

### TOC and Prev-Next Links
Screen Shot 2024-02-06 at 19 24 59

### Top Navigation Bar
Screen Shot 2024-02-06 at 19 40 52

### CODE REVIEW

**Review by crfmc — APPROVED** [review]
Looks good to me! I'll check again if any new updates are made

**Review by Bianca-Morris — APPROVED** [review]
Hey nice job on this! One small thing that would be good to change before merging this:
- Disable "User Guide" link by adding `disableLinksOnLevel1Titles={true}` to line 109 (`<BigDropdownPageTreeMenu>` for DocsNavItem) in `CollapsedNav.js`

Other than that, I think this looks good to go.

**Review by shannonehmsen — APPROVED** [review]
This looks great to me! Thank you for making all of the changes to the pages, its amazing how much better they look!

**Comment by utku-ozturk** [comment]
@Bianca-Morris, Aha, I didn't know there was such a prop `disableLinksOnLevel1Titles`. I added some CSS for an interim solution; the new prop is handy. Thanks for sharing!

**Pull request merged**
